# Generated by Django 4.0.1 on 2022-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('author', models.CharField(default='Anonymous', max_length=50, verbose_name='Author')),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
