# Generated by Django 4.0.1 on 2022-01-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_published', models.DateField()),
                ('time_published', models.TimeField()),
                ('sent', models.BooleanField(default=False)),
            ],
        ),
    ]
