# Generated by Django 4.0.1 on 2022-02-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPost', '0002_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50, verbose_name='Author'),
        ),
    ]
