# Generated by Django 4.0.1 on 2022-02-06 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPost', '0003_alter_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 2, 6)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_published',
            field=models.TimeField(default=datetime.time(16, 34, 38, 11793)),
        ),
    ]
