# Generated by Django 4.0.1 on 2022-02-06 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPost', '0004_alter_message_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_published',
            field=models.TimeField(default=datetime.time(11, 5, 41, 11950)),
        ),
    ]
