# Generated by Django 4.0.1 on 2022-02-06 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPost', '0006_alter_message_time_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='message',
            name='time_published',
            field=models.TimeField(default=datetime.time(11, 25, 30, 568978)),
        ),
    ]
