# Generated by Django 3.2.3 on 2022-02-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPost', '0007_remove_message_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 2, 8)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time_published',
            field=models.TimeField(default=datetime.time(10, 38, 22, 282563)),
        ),
    ]
