# Generated by Django 3.2.3 on 2022-02-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPost', '0008_auto_20220208_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time_published',
        ),
    ]
